부산대 FE_이세형 3주차 과제 Step 1
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #18
Opened 2024-07-09 14:52 UTC by cla6shade

멘토님 안녕하세요!

3주차 PR로 찾아왔습니다.
내일 예비군을 가야해서 모각코에 참여하지 못할 예정이라 어제부터 열심히 달려봤습니다.

### 어려웠던 점

원래 Axios로 request를 넣는 유틸 함수를 만들고, 해당 유틸 함수에서 제네릭으로 request/response type을 지정할 수 있도록 했지만, 가독성이 너무 떨어져서 중간에 갈아엎느라 조금 오래 걸렸습니다 ㅠ

재사용성을 너무 열어둬도 문제고, 안 열어두자니 전부 다 작성해야돼서 적절한 보상점을 찾는 작업이 필요한데 경험이 쌓이면 이번처럼 삽질하는 일은 좀 적어지겠죠?

항상 시간내주셔서 감사합니다!

2024-07-10 01:18 UTC, MiaJLee commented
@cla6shade 
세형님 안녕하세요~ 3주차도 화이팅입니다!

지난 번에 지난 깃 커밋들을 가져올 때 rebase를 사용하는 것을 물어보셨는데,
지난 커밋까지 모두 변경사항으로 노출되다보니 다소 코드 리뷰에 어려움이 있네요.

[dbb6bd6](https://github.com/kakao-tech-campus-2nd-step2/react-gift-goods-list/pull/18/commits/dbb6bd6c47bb34ca7bcc28209607446f95c52caf) 커밋이 지난 주까지의 작업을 가져오신 것 같은데,
해당 커밋은 HEAD 브랜치에 먼저 머지가 되어있어야 할 것 같습니다-!
수정하시고 멘션 부탁드려요.

2024-07-10 22:38 UTC, MiaJLee requested changes
고생하셨습니다 세형님-!
리뷰가 너무 지체될 것 같아 우선 전체적으로 확인했어요.
다음 주차 부터는 이번주 수정사항만 PR에 노출되도록 작업해주심 리뷰에 도움이 될 것 같습니다!
피드백 사항 확인해주세요~

2024-07-10 22:38 UTC, MiaJLee commented on src/utils/index.ts
> +}
꼭 theme, products 에만 사용되진 않을 것 같은 메서드라 좀 더 포괄적인 이름으로 바꿔줘도 좋을 것 같아요.
length의 유무는 load되어도 비어있을 수 있으니 좀 더 명확한 메서드명으로 바꿔볼까요?

```suggestion
export function hasKey(list: Object) {
  return Object.keys(list).length !== 0;
}

export function isEmptyList(list: any[]) {
  return list.length === 0;
}
```

2024-07-10 22:38 UTC, MiaJLee commented on src/constants/RequestURLs.ts
> +};
endpoint를 이렇게 모아두니 한눈에 보이는 것이 좋네요-! 👍

2024-07-10 22:38 UTC, MiaJLee commented on src/dto/index.ts
> +export interface ProductData {
현재 dto 파일을 구분하는 기준이 무엇인가요?
index, Gift, GiftTheme

2024-07-11 03:03 UTC, cla6shade commented
안녕하세요 멘토님!

어제 예비군과 학원 일 강행군으로 11시에 브랜치를 수정하다가 잠들어버렸네요.. 죄송합니다
바쁘신데도 시간내어 리뷰해 주신다는 점을 염두에 두고 바로바로 따라가도록 더 노력하겠습니다

다음 step3부터는 이전 커밋 내역이 뜨지 않도록 base branch에 미리 제가 이전 주차에 작업해둔 사항이 머지되도록 PR해둔 후 작성하면 될까요?

과제를 처음부터 끝까지 제 코드로 완성해보자는 생각으로 지금까지는 이런 식으로 진행했지만,
번거로우시다면 바로 정답 코드 위에 주차별 과제를 수행해보겠습니다.

감사합니다!

2024-07-11 03:06 UTC, cla6shade commented on src/dto/index.ts
> +export interface ProductData {
Gift, GiftTheme는 예전에 서버에서 데이터를 불러오지 않고 사용했던 더미 데이터의 타입이고, index는 서버에서 받아올 실제 데이터의 타입을 담아둔 모듈입니다-!

현재는 ProductData, ThemeData 등 index 모듈에 있는 type만 사용 중이라서 Gift, GiftTheme는 삭제해야 했지만 제가 깜빡하고 삭제를 못했네요..

삭제한 후 다시 푸쉬하겠습니다!

2024-07-11 03:06 UTC, cla6shade commented on src/utils/index.ts
> +}
아하, 생각해보니 더 넓은 용도로 사용할 수 있겠군요
반영해보겠습니다!

2024-07-11 03:29 UTC, MiaJLee approved these changes
예비군까지 병행하다니 너무 고생하셨어요..!
피드백 반영사항 확인하여 머지하겠습니다.

다음주차부터는 이전 커밋들을 올리는 step0 단계를 공지해주실 예정이라고 하네요!
참고해주세요 :)

2024-07-11 03:29 UTC, merged

2024-07-11 04:26 UTC, cla6shade commented
네 감사합니다!!