부산대 FE_최윤성_3주차 과제 제출입니다.
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #27
Opened 2024-07-09 18:05 UTC by yunseong0404

안녕하세요 멘토님 3주차 step1 과제 제출 입니다
문제가 해결되지 않아 제출이 늦었습니다 죄송합니다
메인페이지에서 선물 카테고리를 클릭시 Theme 페이지로 넘어가지 않아서 과제를 모두 해결하지 못했습니다.. themeKey는 바르게 전달이 된것같은데 getCurrentTheme 함수에서 일치하는 theme 데이터가 선택이 되지 않는 것 같습니다 어느부분이 잘못된 것 인지 궁금합니다!!

2024-07-10 08:03 UTC, MiaJLee requested changes
윤성님~ 3째주도 잘 해봅시다-!
질문 관련해서 생각해봄직한 부분에 대해 리뷰 남겼습니다.

추가로, 현재 일부 컴포넌트의 파일명이 `index.tsx` 로 되어있는데,
여러 파일을 열어두었을때 파일 찾기가 쉽지가 않은 것 같아요.
좀 더 컴포넌트를 잘 설명하는 이름으로 변경하시는게 어떨까요?

2024-07-10 08:03 UTC, MiaJLee commented on src/components/features/Home/ThemeCategorySection/index.tsx
> +            <Link to={getDynamicPath.theme(`${theme.key}`)}>
map 돌리실때 key 넣는거 잊지 말아주세요!

왜 리액트에서 map 돌릴 때 key가 필요한지 댓글로 답변 부탁해요-~

2024-07-10 08:03 UTC, MiaJLee commented on src/components/features/Theme/ThemeHeroSection/index.tsx
> +          'https://react-gift-mock-api-ten.vercel.app/api/v1/themes'
반복되는 api의 url 주소 부분은 따로 상수로 빼내서 사용하는게 어떨까요?
`https://react-gift-mock-api-ten.vercel.app`

2024-07-10 08:03 UTC, MiaJLee commented on src/components/features/Theme/ThemeHeroSection/index.tsx
> +  return themeList.find((theme) => themeKey === theme.key);
해당 함수 안에서 themeKey와 themeList가 정상적으로 들어오는지 확인 해보시겠어요?

2024-07-10 08:03 UTC, MiaJLee commented on src/pages/Theme/index.tsx
> +  const currentTheme = getCurrentTheme(themeKey, Themes);
getCurrentTheme이 어떤 시점에 호출되어야 할까요?

2024-07-10 08:03 UTC, MiaJLee commented on src/pages/Theme/index.tsx
> +  console.log(currentTheme);
PR 올리기 전에 콘솔로그는 모두 정리해주세요-!

2024-07-11 06:00 UTC, yunseong0404 commented on src/components/features/Home/ThemeCategorySection/index.tsx
> +            <Link to={getDynamicPath.theme(`${theme.key}`)}>
DOM이 업데이트 할때 가상 DOM을 이용해 변화된 부분만 업데이트를 하는데 key가 없을 경우 요소를 식별할 수 없어 모든 요소를 재렌더링해야 하는 문제가 발생하여 map에서 key가 필요합니다!

2024-07-11 23:44 UTC, MiaJLee requested changes
윤성님-! 추가 피드백 확인 부탁드려요~
본문에 질문 주신 사항은 해결이 되셨을까요?

2024-07-11 23:44 UTC, MiaJLee commented on src/pages/Theme/ThemePage.tsx
> +    };
해당 api를 get 하는 함수가 여러 파일에서 반복되고 있는데요!
공통되는 URL을 가지고 있는, api path를 파라미터로 받는 공용 함수를 사용해보는 것은 어떨까요?

2024-07-12 02:10 UTC, yunseong0404 commented
ThemePage.tsx에서 useEffect가 렌더링 이후에 실행되어 themes에 값이 업데이트 되지 않아 if 문을 추가하여 문제를 해결하였습니다. 그런데 이 방법보다 더 나은 해결책이 있는지 궁금합니다!

2024-07-12 05:05 UTC, MiaJLee requested changes
윤성님 한가지만 더 확인해주세요-!

2024-07-12 05:05 UTC, MiaJLee commented on src/pages/Theme/ThemePage.tsx
> +
@yunseong0404 
윤성님~ themeKey가 변할 때마다 useEffect를 실행시킨다면 어떨까요?

2024-07-12 05:12 UTC, yunseong0404 commented on src/pages/Theme/ThemePage.tsx
> +
useEffect 배열에 추가하였습니다!

2024-07-12 05:14 UTC, MiaJLee approved these changes
고생하셨습니다 :)

2024-07-12 05:14 UTC, merged