부산대 FE_차기은_3주차 과제 Step2
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #36
Opened 2024-07-10 06:50 UTC by harugi7

2024-07-10 06:57 UTC, harugi7 commented
미아 멘토님 step2와 step1 때 피드백 주신거 반영해보았습니다~!
특히 step2는 구현하면서도 잘 하고있나 확신이 들지 않더라구요... 
데이터가 없을 때에도 loading이 꽤 오래 걸리는데 잘 구현한 부분인지 확인 부탁드립니다...!
이번 step도 잘 부탁드립니다ㅎㅎ🥰

2024-07-10 08:03 UTC, MiaJLee requested changes
기은님 오늘도 고생하셨습니다-!
피드백 확인 부탁드려요~

2024-07-10 08:03 UTC, MiaJLee commented on src/components/api/index.tsx
> +};
크으으 … .. .. . . … .!!! 👍 x 10000000

맨 앞의 `?` 까지 함수 안에 있어도 될 것 같아요!

2024-07-10 08:03 UTC, MiaJLee commented on src/components/api/index.tsx
> +        case 400:
error case 와 error message도 각각 타입, 상수로 빼면 어떨까요?

2024-07-10 08:03 UTC, MiaJLee commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +        const data = await fetchData(`/api/v1/ranking/products`, queryParams);
👍👍👍👍👍👍👍👍👍👍👍👍

2024-07-10 08:03 UTC, MiaJLee commented on src/components/features/Theme/ThemeGoodsSection/index.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
loading 초기값을 true로 하신 이유가 있을까요??
주로 try 문에서 loading true 한 케이스를 보아서요-!
동일한 화면에서 themeKey가 변경되어 useEffect가 다시 호출되었을때 loading 값은 어떻게 될까요?

2024-07-11 05:25 UTC, harugi7 commented on src/components/features/Theme/ThemeGoodsSection/index.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
useEffect가 다시 호출되었을때 데이터를 다시 로드하는 동안 로딩 스피너를 다시 보여줘야하기 때문에  loading 상태를 true로 설정하여줘야하군요! 수정하겠습니다!!

2024-07-11 05:35 UTC, harugi7 commented
미아 멘토님~! 말씀해주신 부분들 수정하였습니다! 항상 꼼꼼히 봐주셔서 감사합니다🥹

2024-07-11 08:40 UTC, MiaJLee approved these changes
LGTM! 고생하셨습니다 기은님 👏

2024-07-11 08:40 UTC, MiaJLee commented on src/components/api/index.tsx
> +const handleFetchError = (error: unknown, endpoint: string) => {
따로 핸들링하는 메서드까지 만드셨네요 ! 👍

2024-07-11 08:40 UTC, merged