강원대 FE_김정윤 3주차 과제 Step2
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #42
Opened 2024-07-10 15:02 UTC by wjdsbs

안녕하세요 멘토님! 3주차 과제 Step2 제출합니다.

2024-07-10 17:11 UTC, yujo11 requested changes
안녕하세요 정윤님!

리뷰가 조금 늦어져 step1, step2를 동시에 리뷰하게 되었는데요

step1에 남긴 코멘트들도 이 PR에 같이 반영해주시면 좋을거 같습니다 ㅎㅎ

그리고 step1 merge 후 컨플릭트가 발생하고 있는데 이 부분도 resolve 하신 후에 리뷰요청 다시 주시면 좋을거 같아요!

고생 많으셨습니다 ~~ 👍 👍 👍

2024-07-10 17:11 UTC, yujo11 commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  const [fetchState, setFetchState] = useState<FetchState<GoodsData[]>>({
오 객체로 관리하는 것도 좋은 아이디어네요 ㅎㅎ 👍

2024-07-10 17:11 UTC, yujo11 commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +        )}
중첩 된 삼항연산자는 코드를 보기 어렵게 만드는데요. 이 부분을 어떻게 개선해 볼 수 있을까요? ㅎㅎ

2024-07-12 12:40 UTC, wjdsbs commented
STEP1 피드백에서 말씀해주신 대로 utils/api/index.ts에 useFetch 훅을 만들어 재사용해보았습니다.
GoodsRankingSection에서는 잘 동작하던 훅이 ThemeGoodsSection에 적용하자마자 무한 렌더링되는 문제가 발생해 useMemo로 해결하였습니다.!!
중첩된 삼항연산자도 renderContent 함수에 넣어 if문으로 분리하여 작성해보았습니다. 혹시 더 괜찮은 개선 방식이 있다면 조언 부탁드립니다!!

2024-07-13 08:36 UTC, yujo11 approved these changes
고생 많으셨습니다 정윤님!

step3 리뷰요청 기다리겠습니다 ㅎㅎ 👍

2024-07-13 08:36 UTC, merged