전남대 FE_정서윤 3주차 과제 step1~2
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #44
Opened 2024-07-10 17:47 UTC by yunn23

안녕하세요 멘토님 step1 과제 중 문제 해결이 되지 않아 질문드립니다.

**메인페이지 테마 섹션인 ThemeCategorySection/index.tsx에서 map 함수로 카테고리들을 나열할때 이미지, 텍스트 등은 잘 나타나는데 Link 태그가 작동하지 않습니다. 각 테마 컴포넌트를 클릭하면 해당 테마 페이지로 이동해야 하는데 현재는 계속 메인페이지가 로딩됩니다.**

보호된 라우트로 처리되어 있어 테마페이지로의 직접 접근도 불가하기에 현재 step1의 테마페이지 api도 구현하지 못한 상태입니다. 페이지 이동 문제가 해결된 이후 구현하도록 하겠습니다. 혼자 해결해보려고 많이 시도했으나 시간이 많이 지체되어 부득이하게 다 구현하지 못하고 pr 제출합니다 ㅜㅜ..

2024-07-12 11:54 UTC, taehwanno requested changes
리뷰 코멘트 드려요! 제가 드린 질문에는 리뷰 코멘트로 답변 직접 남겨주시면 좋을 거 같아요.

2024-07-12 11:54 UTC, taehwanno commented on package.json
> +    "format": "prettier --write 'src/**/*.{js,jsx,ts,tsx,json,css,scss,md}'"
`npm run format` 실행시 prettier 적용되지 않은 코드들이 몇 개 있네요. 수정 부탁드려요~!

2024-07-12 11:54 UTC, taehwanno commented on src/pages/Theme/index.tsx
> +      } catch (err) {
`fetchThemes`가 실패했을 때 에러 콘솔만 남기고 `isLoading`이 `false`로 변하는데 사용자는 이때 별다른 안내를 받지 못하고 not found 페이지로 이동되겠죠. 이를 위해 에러 핸들링 개선해보면 좋을 거 같습니다!

2024-07-12 11:54 UTC, taehwanno commented on src/components/features/Theme/ThemeHeroSection/index.tsx
>  import styled from '@emotion/styled';
> step2의 error, loading 상태 핸들링시 비동기 데이터를 불러오는 파일에 error와 loading 핸들링 코드를 넣게 되면서 코드가 중복된다는 느낌을 받았습니다. 혹시 error나 loading 상태 핸들링도 한 파일에서 구현하고 불러오는 형태로 작성해야 하는 걸까요?

코드 중복된다는 느낌을 받으신 코드가 아래 상황들 맞으실까요? 맞다면 중복되는 코드의 이유는 무엇이며 어떻게 개선해볼 수 있을까요?

1. https://github.com/yunn23/react-gift-goods-list/blob/21be9601f238a6c92cfda07dccc1b62dceca90ba/src/components/features/Theme/ThemeHeroSection/index.tsx#L26-L50
2. https://github.com/yunn23/react-gift-goods-list/blob/21be9601f238a6c92cfda07dccc1b62dceca90ba/src/components/features/Theme/ThemeGoodsSection/index.tsx#L24-L47
3. https://github.com/yunn23/react-gift-goods-list/blob/21be9601f238a6c92cfda07dccc1b62dceca90ba/src/components/features/Home/GoodsRankingSection/index.tsx#L28-L58

2024-07-12 11:54 UTC, taehwanno commented on src/api/api.ts
> +  nextPageToken?: string;
```suggestion
  nextPageToken?: string | null;
```

oas에 `nullable: true`로 표현되어 있지는 않긴 한데 description에 `만약 없다면 null`로 적혀있어서 nullable 표시해주는게 좋겠습니다.

2024-07-12 11:54 UTC, taehwanno commented on src/api/api.ts
> +  }
다른 API 구현 코드와는 다르게 246~249번 라인에서 일부 에러를 대응하려고 하셨네요.
해당 방향으로 구현하신 이유는 어떤걸까요?

2024-07-12 11:54 UTC, taehwanno commented on src/api/api.ts
> +    const response = await axiosInstance.post<PostOrderResponse>('/api/v1/order', data);
```suggestion
export const postOrder = async (data: PostOrderRequest): Promise<void> => {
  try {
    const response = await axiosInstance.post<void>('/api/v1/order', data);
```

void 타입은 따로 타입 만들기보다는 직접 inline 하셔도 괜찮습니다.

2024-07-12 11:54 UTC, taehwanno commented on src/pages/Theme/index.tsx
> +    const getTheme = async () => {
```suggestion
    setIsLoading(true);
    const getTheme = async () => {
```

지금처럼 mount 할 때 데이터 요청을 한다면 15번 라인에 로딩 상태 초기값을 true로만 전달해두고, 비동기 요청 전에 isLoading을 true로 변경해주지 않아도 되겠지만 기능 요구사항이 변화하거나 리팩토링 하면서 함수가 추출되어 사용되거나 등등 시간에 따라 코드가 변화할 때는 mount가 아닌 상황에서도 활용될 수 있기에 비동기 요청 전에 한 쌍으로 로딩 상태를 변화시키는걸 추천드려요.

2024-07-12 17:53 UTC, yunn23 commented on package.json
> +    "format": "prettier --write 'src/**/*.{js,jsx,ts,tsx,json,css,scss,md}'"
step3,4 브랜치에서 수정하였습니다!

2024-07-13 14:59 UTC, yunn23 commented on src/components/features/Theme/ThemeHeroSection/index.tsx
>  import styled from '@emotion/styled';
코드가 중복되는 이유는 각 컴포넌트가 데이터 요청과 에러 처리를 독립적으로 수행하고 있기 때문입니다. 코드의 재사용성을 높이기 위해 커스텀훅을 사용하여 여러 컴포넌트에서 커스텀훅을 호출하는 형태로 사용하면 좋을 것 같습니다.

2024-07-13 15:09 UTC, yunn23 commented on src/pages/Theme/index.tsx
> +      } catch (err) {
step3 브랜치에서 에러핸들링 개선했습니다!
<img width="611" alt="image" src="https://github.com/user-attachments/assets/0294b1ae-bbc5-48ae-8a92-7564c48ad854">

2024-07-13 15:12 UTC, yunn23 commented on src/api/api.ts
> +  nextPageToken?: string;
step3 브랜치에서 반영하였습니다
<img width="372" alt="image" src="https://github.com/user-attachments/assets/caa5aa8e-714d-4589-a7a0-b1c890817c89">

2024-07-13 15:21 UTC, yunn23 commented on src/api/api.ts
> +  }
api호출 함수에서도 에러핸들링 코드를 작성해보려고 코드의 마지막 줄에서 에러 대응 코드를 작성해보았습니다. 다른 api 코드와 일관성을 맞추는 것이 좋을 것 같아 현재 아래 코드로 수정하였습니다. (step3 브랜치에서)

<img width="672" alt="image" src="https://github.com/user-attachments/assets/a4ab9d66-213c-44d2-b939-f59476bd3995">

2024-07-13 15:25 UTC, yunn23 commented on src/api/api.ts
> +    const response = await axiosInstance.post<PostOrderResponse>('/api/v1/order', data);
step3 브랜치에서 반영하였습니다.

2024-07-13 16:04 UTC, yunn23 commented on src/pages/Theme/index.tsx
> +    const getTheme = async () => {
오 네 알겠습니다! step3 브랜치에서 반영하였습니다.

2024-07-14 06:02 UTC, taehwanno commented on src/components/features/Theme/ThemeHeroSection/index.tsx
>  import styled from '@emotion/styled';
넵, 잘 말씀해주셨네요. 비동기 요청은 데이터 요청, 데이터 캐싱, 로딩 및 에러 상태 관리를 보통 필요로 하는데 직접 구현하다보니 중복되는 코드들이 꽤 있다고 느끼실 수 있어요. [react-query](https://tanstack.com/query/latest/docs/framework/react/overview)가 이런 문제를 쉽게 풀 수 있도록 해주는 도구 중 하나에요.

2024-07-14 06:02 UTC, taehwanno approved these changes
고생하셨어요!

2024-07-14 06:02 UTC, merged