강원대 FE_이채연 3주차 과제
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #45
Opened 2024-07-11 05:28 UTC by codus1718

2024-07-11 05:37 UTC, codus1718 commented
저장을 하지 않고 commit을 하여 다시 commit함

2024-07-14 12:08 UTC, lazy-sky requested changes
안녕하세요, 채연님

3주차 과제 수고하셨습니다!

2024-07-14 12:08 UTC, lazy-sky commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +    ['rankingProducts', filterOption],
쿼리키값은 따로 변수화하여 관리해주는 것이 유지보수 관점에서 좋습니다.

2024-07-14 12:08 UTC, lazy-sky commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  if (isLoading) {
로딩 및 에러 상태에 대한 적절한 렌더링 처리를 해주셨네요!

2024-07-14 12:08 UTC, lazy-sky commented on src/components/features/Theme/ThemeHeroSection/index.tsx
> +  const currentTheme = data?.themes.find((theme) => theme.key === themeKey);
로딩 및 에러 분기 처리를 빠져 나왔는데 `data`가 없는 경우도 있을까요?

2024-07-14 12:10 UTC, merged