강원대 FE_최서린_3주차 과제
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #60
Opened 2024-07-11 17:39 UTC by seorinnn

안녕하세요 멘토님! 항상 꼼꼼하게 피드백 해주셔서 감사합니다.

### 아래 문제는 해결하였습니다.
### 과제를 더 진행하여 리뷰 요청 다시 하도록 하겠습니다!

---
3주차 과제를 진행하고 있는데,
테마 카테고리 부분을 클릭하면 원하는 주소로 이동이 되지 않습니다.

예를 들어 생일 카테고리를 클릭하면, 주소창에 이동을 원하는 올바른 주소인
`http://localhost:3000/theme/theme_birth`
위 주소가 정말 잠깐 짧은 시간동안 떴다가
`http://localhost:3000/`
이 루트 경로로 이동됩니다. 모든 테마들을 클릭해도 다 위와 같이 잠깐 제대로 된 주소가 뜨고
루트 경로로 이동됩니다.

잠깐이라도 제대로 된 주소가 뜬다는 것은 
```
{themes.map((theme) => (
            <Link to={getDynamicPath.theme(theme.key)} key={theme.id}>
              <ThemeCategoryItem image={theme.imageURL} label={theme.label} />
            </Link>
          ))}
```

이 부분의 문제는 아닌 것 같은데 ThemePage 부분에 문제가 있는 것인지 ..
이곳저곳 건드려봐도 이동이 되지 않는 문제가 해결되지 않고 ..
이 문제가 해결이 안되면 다음 단계가 진행되지 않아 질문드립니다 ㅠㅠ
늦게 질문드려 죄송합니다 ..

---

2024-07-12 09:16 UTC, lazy-sky requested changes
안녕하세요, 서린님.

짧은 시간 안에 겪고 있는 문제를 스스로 트러블슈팅하는데 성공하셨군요. 대단합니다!

크게 변경해야 될 부분은 없고, 변수명 컨벤션 위주로 참고용 마이너한 코멘트만 남겨두었습니다. 수고하셨습니다.

2024-07-12 09:16 UTC, lazy-sky commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  const { goodsList } = useGoodsRanking(filterOption);
minor) 훅의 이름은 `useGoodsRanking`인데 get하는 데이터의 이름은 `goodsList`네요. 이름을 통일하는 편이 더 잘 읽힐 거 같습니다.

2024-07-12 09:16 UTC, lazy-sky commented on src/hooks/useThemes.ts
> +  const [loading, setLoading] = useState<boolean>(true);
불리언 데이터 타입의 변수는 `is`, `has` 등을 prefix로 사용하는 것이 좋습니다. e.g., `isLoading`

2024-07-12 09:16 UTC, lazy-sky commented on src/components/features/Home/ThemeCategorySection/index.tsx
> +          {themes.map((theme) => (
`map`을 활용한 간소화 좋습니다!

2024-07-12 09:16 UTC, lazy-sky commented on src/hooks/useGoodsRanking.ts
> +    fetchGoodsRanking();
minor) 이렇게 `useEffect`에서 선언 후에 바로 사용하는 함수는 [즉시 실행 함수](https://developer.mozilla.org/ko/docs/Glossary/IIFE) 문법을 활용할 수도 있습니다. (그게 더 좋다는 뜻은 아니고, 알아두시면 좋을 거 같아서 말씀드립니다.)

2024-07-12 09:16 UTC, lazy-sky commented on src/hooks/useThemes.ts
> +        setError('테마를 가져오는데 실패했습니다.');
저장하는 정보가 에러 자체라기보단 에러 메시지에 가까운 거 같네요. 일반적으로 에러라하면 statusCode 등을 담은 객체가 예상됩니다.

2024-07-12 09:16 UTC, lazy-sky commented on src/pages/Theme/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
린트 룰은 가급적이면 무시하지 않는 게 좋습니다. 무시해야만 내가 의도한대로 동작한다면 구조를 잘못 짰을 가능성이 높습니다.

2024-07-13 17:32 UTC, seorinnn commented
안녕하세요 멘토님 !!

step1, step4 부분을 제출한 후,
멘토님의 피드백을 받아 코드를 수정해 커밋해두었습니다!
더 고칠 부분이 있다면 말씀해주시면 감사하겠습니다 ㅎㅎ

또한 step2 를 수행하여 커밋하였습니다.
이 부분도 피드백해주시면 감사하겠습니다!!

step3 는 아직 수행하지 못해서..
최대한 열심히 노력하여 해내보겠습니다!

또한 두 가지 질문이 있어 질문 드립니다 ㅎㅎ

---

#### 질문 1
- 3주차 과제 원본 레포지토리에서는 Theme 폴더 안에 ThemeHeroSection, ThemeGoodsSection 폴더가 있고 각 폴더 안에 index.tsx 파일이 있는 상태로 주어졌습니다.
- 그런데 이렇게 하지 않고 Theme 폴더 안에 바로 ThemeHeroSection.tsx, ThemeGoodsSection.tsx 파일이 있도록 하는 방식이 같다고 생각이 드는데, 무엇이 더 좋은 것인지 궁금합니다!

#### 질문 2
- 현재 src/components/features/Home/GoodsRankingSection/index.tsx 에서 loading, error 시 UI 대응을 해 놓은 상태입니다.
```
const LoadingWrapper = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 40vh;
`;

const ErrorWrapper = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 15vh;
  text-align: center;
`;
```
- 위와 같이 코드를 작성하였는데 에러 문구나 로딩중인 애니메이션이 가운데 정렬이 되지 않습니다 ㅠㅠ 원인이 무엇인지 모르겠어서 질문드립니다!

---

항상 피드백해주셔서 감사합니다.
저도 더 노력하겠습니다!

2024-07-14 12:25 UTC, lazy-sky requested changes
- 질문1
누차 말씀드렸듯 뭐가 더 좋다고 단언하긴 어렵습니다. 저는 `indext.tsx` 파일을 쓰는 것을 선호합니다. 코드의 동작과는 전혀 관련이 없기 때문에 결국 개발 당사자가 더 보기에 좋다고 생각하는 구조가 더 좋습니다.  


질문2
개발자 도구에서 실제로 컴포넌트가 얼마나 영역을 차지하는지 확인해보셨나요? 아마 확인해보시면width가 이상하다는 걸 볼 수 있으실 겁니다. flexbox가 어떤식으로 너비와 높이를 차지하는지 공부해보시는 걸 추천드립니다.

2024-07-14 12:28 UTC, merged