강원대 FE_정다연_3주차 과제 STEP2
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #62
Opened 2024-07-12 03:58 UTC by dandamdandam

멘토님 안녕하세요,
이번 단계에서는 로딩과 에러 상태를 유저에게 보여주는 작업을 처리했습니다!

관련 내용 [README](https://github.com/dandamdandam/react-gift-goods-list/blob/cf9089abb3ee14d818b51f06ce42115f59a6d7a8/README.md)에 정리해두었습니다.

2024-07-12 09:29 UTC, lazy-sky requested changes
안녕하세요, 다연님
.

대체로 과제를 잘 수행해주고 계십니다. 크게 변경해야 될 부분은 없고, 참고하면 좋을 것 정도로만 코멘트를 달아두었습니다. 수고하셨습니다.

2024-07-12 09:29 UTC, lazy-sky commented on src/components/common/LoadingUI/index.stories.tsx
> +            rhdiddl
minor) 의미없는 문자열이 들어갔네요.

2024-07-12 09:29 UTC, lazy-sky commented on src/hooks/useData.ts
> +type Returns<T> = {
제네릭을 활용할 줄 아시는군요! 👍

2024-07-12 09:29 UTC, lazy-sky commented on src/hooks/useData.ts
> +    const [httpStatusCode, setHttpStatusCode] = useState<number>(200);
기본값을 200으로 상정했네요. 이게 문제가 될 가능성은 없을까요?

2024-07-12 09:29 UTC, lazy-sky commented on src/pages/Error.tsx
> +    const errorOrigin = useParams().error_origin;
코드의 일관성을 위해 구조 분해 할당을 사용하자면 아래와 같이 표현할 수도 있습니다. 
`const { error_origin: errorOrigin } = useParams();`

2024-07-12 09:29 UTC, lazy-sky commented on src/pages/Main/RankingView/RankingList.tsx
> +            {items?.isLoading ? (
컴포넌트를 렌더링하는 부분에서 삼항 연산자는 뎁스를 깊게 만들어 가독성을 떨어뜨리는 경향이 있습니다. 그래서 저는 early return 패턴을 선호하는 편인데 이런 패턴도 참고하시면 좋을 거 같습니다.

```tsx
if (isLoading) {
  return <Loading />
}

if (isError) {
  <Error />
}

return (
 // ...
)

```

2024-07-12 09:29 UTC, lazy-sky commented on src/pages/Theme/index.tsx
>          const index = themes?.data?.themes.findIndex((_theme) => _theme.key == themeKey) ?? -1;
`find` 대신 `findIndex`를 쓰신 이유가 있으신가요?

2024-07-13 11:22 UTC, dandamdandam commented on src/hooks/useData.ts
> +    const [httpStatusCode, setHttpStatusCode] = useState<number>(200);
해당 값은 데이터를 가져오는 중 에러가 발생했을 때 200 외의 값으로 고쳐집니다. 오로지 에러핸들링을 위해 쓰이는 값이며, 발생할 수 있는 다양한 문제에 대해 간편하게 저장하고 그에 맞게 대응할 수 있기 않을까 하여 boolean 값이 아닌 httpStatus를 저장하였습니다.

성공 상태가 200이 아닌 값이 들어온다면 문제가 될 수도 있습니다.
하지만 해당 훅이 현재로써는 단순히 데이터를 가져올 때만 쓰이고, 이 경우 제가 아는 한 성공값이 200 외에는 없습니다.

2024-07-13 12:10 UTC, dandamdandam commented on src/components/common/LoadingUI/index.stories.tsx
> +            rhdiddl
수정했습니다!
https://github.com/kakao-tech-campus-2nd-step2/react-gift-goods-list/pull/62/commits/7ad8dabf1ac7d13a27afde75230ed248674efb94

2024-07-13 12:11 UTC, dandamdandam commented on src/pages/Error.tsx
> +    const errorOrigin = useParams().error_origin;
수정했습니다.
브랜치 변경 중 커밋이 합병되어 위와 커밋이 같습니다..! https://github.com/kakao-tech-campus-2nd-step2/react-gift-goods-list/pull/62/commits/7ad8dabf1ac7d13a27afde75230ed248674efb94

2024-07-13 12:13 UTC, dandamdandam commented on src/pages/Main/RankingView/RankingList.tsx
> +            {items?.isLoading ? (
수정했습니다!
https://github.com/kakao-tech-campus-2nd-step2/react-gift-goods-list/pull/62/commits/52d539ddb6c2c0c081d3bdd4756e6d15eca25e41

수정하는 과정 중에 서로 다른 두 api에서 데이터를 가져오는 pages/theme/index 파일의 내용이 복잡한 것 같아, 컴포넌트로 따로 나누었습니다. (ThemeHeaderRender, ProductsRender)

2024-07-13 12:15 UTC, dandamdandam commented on src/pages/Theme/index.tsx
>          const index = themes?.data?.themes.findIndex((_theme) => _theme.key == themeKey) ?? -1;
코드 짤 당시에 find 함수를 감안하지 않아서 index를 썼습니다. find로 바꾸면 코드가 더 간결해지고 보기 편해질 것 같아 수정하였습니다.
https://github.com/kakao-tech-campus-2nd-step2/react-gift-goods-list/pull/62/commits/b573346c5abcc5878b023e65f2752f6196fadf68

2024-07-14 12:33 UTC, lazy-sky commented on src/hooks/useData.ts
> +    const [httpStatusCode, setHttpStatusCode] = useState<number>(200);
아마 이 과제에서는 크게 문제가 없겠죠. 하지만 실제 상황에서는 다소 위험할 수 있습니다. 클라이언트 개발자는 서버의 상황을 불신해야 합니다. 에러 핸들링 처리는 그런 긍정적인 불신의 결과물입니다. 서버 상황이 어떠하든 유저에게 적절한 화면을 보여준다.

2024-07-14 12:33 UTC, merged