강원대 FE_이예지_3주차 과제 STEP2
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #65
Opened 2024-07-12 05:30 UTC by yeahzee0421

멘토님 안녕하세요:D 
3주차 과제 step2 제출합니다
step2에서는 HTTP status에 따라 에러 핸들링 하는 방법에 대해 가장 고민을 많이 한 것 같습니다.

우선 데이터를 get 해오는 fetchData에서 데이터를 잘 받아왔는지 확인하는 `ok`를 반환하도록 하고,
```typescript
export const fetchData = async <T>(
  apiEndpoint: string,
  params?: object,
): Promise<{ data: T; ok: boolean }> => {
  const res = await apiClient.get<T>(apiEndpoint, { params });
  const ok = res.status === 200;
  return { data: res.data, ok };
};
```
ok가 true라면 fetchState의 상태를 업데이트 해주도록 구현했습니다.
```typescript
if (res.ok) {
    const fetchedData = res.data.themes;
    setFetchState({
      isLoading: false,
      isError: false,
      isDataNull: fetchedData.length === 0,
      data: fetchedData,
      errorMessage: null,
    });
  }
```
에러가 발생했을 때 해당 에러의 메세지를 가져오는 getErrorMessage 함수를 작성했습니다.
```typescript
export const getErrorMessage = (error: unknown) => {
  if (error instanceof Error) return error.message;
  return String(error);
};
```
catch문으로 error를 잡아줄 때 getErrorMessage 함수를 사용해서 발생한 에러에 대한 메세지를 가져오도록 구현해보았습니다.
```typescript
catch (error) {
    console.error(getErrorMessage(error));
    setFetchState({
      isLoading: false,
      isError: true,
      isDataNull: true,
      data: null,
      errorMessage: getErrorMessage(error),
    });
  }
```
이전까지는 catch문 사용해서 기계적으로 에러를 핸들링 해왔던 것 같은데 이번 기회에 status에 따른 에러 핸들링에 대한 고민을 해볼 수 있었던 것 같아서 좋았습니다. 
제 코드 살펴보시고 피드백 주시면 감사하겠습니다 !!

2024-07-13 07:39 UTC, yujo11 requested changes
안녕하세요 예지님~ 잘 구현해주셨네요 ㅎㅎ

간단한 코멘트들 남겼으니 확인 해보시면 좋을거 같아요! 고생 하셨습니다 ~~~ 👍 👍 👍

2024-07-13 07:39 UTC, yujo11 commented on src/api/constants/apiPath.ts
> +export const API_ENDPOINT = {
👍 👍 👍

2024-07-13 07:39 UTC, yujo11 commented on src/api/fetchData.ts
> +export const fetchData = async <T>(
한칸 떨어져 있으면 좋겠네요 ㅎㅎ
```suggestion
import apiClient from '.';

export const fetchData = async <T>(
```

2024-07-13 07:39 UTC, yujo11 commented on src/api/types/fetchState.ts
> +}
제네릭을 잘 활용해주셨네요 ㅎㅎ 👍

2024-07-13 07:39 UTC, yujo11 commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  }
깔끔하네요! Suspense나 ErrorBoundary를 활용해서 컴포넌트 외부에서 Loading, Error 상태를 처리하고 컴포넌트 내부에서는 하나의 로직(성공하는 경우)에만 집중할 수 있도록 해보셔도 좋을거 같아요 ㅎㅎ

2024-07-13 07:39 UTC, yujo11 commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  if (fetchState.isDataNull || fetchState.data === null) {
여기서도 `data`가 null인지 확인하고 있다면 `isDataNull` 필드가 유효하게 사용되지 않고 있는거 같은데 해당 필드가 꼭 필요할지 고민해보셔도 좋을거 같네요 ㅎㅎ

2024-07-13 11:17 UTC, yeahzee0421 commented on src/api/fetchData.ts
> +export const fetchData = async <T>(
넵 ㅎㅎ 수정 진행했습니다
https://github.com/yeahzee0421/react-gift-goods-list/commit/50f1b6b760a506c57759c1607cf2d4746aa3ec30

2024-07-13 11:18 UTC, yeahzee0421 commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  }
오! 네네 step3에서 리액트 쿼리 사용하면서 알려주신 내용들도 함께 사용해보겠습니다 :D!!

2024-07-13 11:30 UTC, yeahzee0421 commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  if (fetchState.isDataNull || fetchState.data === null) {
앗 네 저도 코드 작성하면서 그 부분에 대한 고민을 했는데 데이터를 불러온 뒤에 setFetchState에서 받아온 데이터가 null인지를 체크해도 `fetchState.data===null` 조건을 추가로 넣어주지 않으면 아래와 같은 에러가 뜨더라구요..
```
'GoodsData[] | null' 형식은 'GoodsData[]' 형식에 할당할 수 없습니다.
  'null' 형식은 'GoodsData[]' 형식에 할당할 수 없습니다.ts(2322)
```
![image](https://github.com/user-attachments/assets/382e4a8f-cd0b-4273-a10c-084dde3080ad)

그래서 fetchState에 데이터가 있으면 goodsList가 렌더되도록 수정했습니다. 
```
{fetchState.data && <GoodsRankingList goodsList={fetchState.data as GoodsData[]} />}
```
타입 문제 같아 보이는데 아예 `isDataNull` 필드를 삭제하는 것이 좋을까요..?
https://github.com/yeahzee0421/react-gift-goods-list/commit/6faf790323cecea71af577a614a227661285795f

2024-07-14 01:15 UTC, yujo11 approved these changes
고생 많으셨습니다 예지님 !! ㅎㅎ 👍 👍👍

2024-07-14 01:15 UTC, yujo11 commented on src/api/fetchData.ts
> +
👍  👍 👍

2024-07-14 01:15 UTC, yujo11 commented on src/api/types/fetchState.ts
> +  isDataNull?: boolean;
유효하게 사용되지 않는 필드라면 옵셔널 대신 제거하는 것도 하나의 방법일거 같네요 ㅎㅎ

2024-07-14 01:15 UTC, merged