부산대 FE_차기은_3주차 과제 step3, 4
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #68
Opened 2024-07-12 06:06 UTC by harugi7

2024-07-12 06:09 UTC, harugi7 commented
3주차 과제 완료하였습니다! 
기존 코드에서 react-query를 이용해 코드를 리팩토링하는 일이 정말 쉽지 않음을 느꼈습니다😅
이번주 마지막 피드백도 잘 부탁드립니다!!!

2024-07-12 13:23 UTC, MiaJLee requested changes
기은님~ 리뷰 확인해주세요!

2024-07-12 13:23 UTC, MiaJLee commented on src/components/features/Theme/ThemeGoodsSection/index.tsx
> +  );
👍👍👍👍👍

2024-07-12 13:23 UTC, MiaJLee commented on src/index.tsx
> +root.render(<App />);
StrictMode 제거하신 이유가 있을까요??

2024-07-12 13:23 UTC, MiaJLee commented on src/components/features/Theme/ThemeGoodsSection/index.tsx
본 파일에서 `renderContent` 메서드가 두 번 선언되고 있어요.
PR 제출 전에는 꼭 개발서버 실행하고 에러나 워닝을 확인해주세요-!

2024-07-13 14:07 UTC, harugi7 commented
미아 멘토님! 말씀하신 부분 수정하였습니다. 메서드가 두번 선언되어서 렌더링이 두번 되는게 strictMode 때문이라고 판단하여 삭제했었습니다ㅠㅠ. 함수를 밖으로 빼내어서 해결하였습니다. 
이번주도 정성스런 피드백 주시느라 고생 많으셨습니다...! 감사합니다!!🥰

2024-07-14 11:56 UTC, MiaJLee approved these changes
고생하셨습니다-!

2024-07-14 11:56 UTC, merged