부산대 FE_이세형 3주차 Step 3, 4
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #73
Opened 2024-07-12 07:15 UTC by cla6shade

안녕하세요 멘토님!

3주차 step 3로 찾아왔습니다.

본래 IntersectionObserver을 사용하여 inView 훅을 직접 구현하고, suspense와 Errorboundary까지 사용해보는 것이 목표였지만..
생각보다 오래 걸리고 여러 문제점이 겹쳐서 목표를 완성하지는 못했습니다.

선택사항을 전부 구현해보자는 구체적인 목표가 있어서, 주말에 여행 일정이 끝나는대로 목표를 완성해볼 생각입니다.

### 어려웠던 점

intersectionObserver을 사용하는것 까지는 어렵지 않았지만, `bottom section이 뷰포트에 전부 나타났을 때`, `페이지가 렌더링 되었을 때` 다음 페이지를 페치하도록 구현했더니 페이지가 렌더링 되었을 때 bottom section이 뷰포트에 전부 나타나서 결과적으로는 페이지에 딱 들어갔을때 두 번씩 페치되는 문제점이 있었습니다.. 제 구현상의 문제인가 싶어 라이브러리도 설치해봤지만 달라지는 점은 없더라구요..ㅎㅎ 

아직 해결은 못했는데 조금만 더 고민해보면 해결할 수 있을 것 같습니다!

항상 시간내어주셔서 감사합니다. 
리뷰 달아주시는대로 최대한 빨리 반영해보겠습니다!

2024-07-12 13:37 UTC, MiaJLee requested changes
고생하셨습니다 세형님~
과제 요구사항에 더해 추가적인 스펙까지 구현하신 것 👍  대단해요!

제 로컬에서 실행 시, 리액트 쿼리의 에러 케이스가 발생하고 있네요.
해당 에러 예외처리가 필요할 것 같습니다-!
<img width="405" alt="스크린샷 2024-07-12 오후 10 33 51" src="https://github.com/user-attachments/assets/6d108d0a-2a85-4c02-8e36-9a14f0d60de1">

2024-07-12 13:37 UTC, MiaJLee commented on src/components/molecules/skeleton/ProductSkeletonGrid.tsx
스켈레톤 구현까지! 정말 깔끔하게 정리해주셨네요! 👍

2024-07-12 13:37 UTC, MiaJLee commented on src/utils/index.ts
> +}
아직 사용되지 않고 있는 유틸 함수로 보이는데요~
어떤 용도로 해당 유틸을 생성하셨는지 궁금합니다~!

2024-07-13 09:26 UTC, cla6shade commented on src/utils/index.ts
> +}
IntersectionObserver을 사용할때 콜백이 너무 자주 호출돼서 완급조절(?)이 좀 필요해보였습니다.
전에 step1의 강의에서 loadash의 throttle 함수를 구현했던 기억이 있어서 한 번 사용해보려고 했습니다..!

2024-07-13 09:29 UTC, cla6shade commented
안녕하세요 멘토님~!

이번에도 정성껏 피드백해주셔서 정말 감사드립니다!

피드백해주신 내용은 현재 반영했지만 아직까지 제가 원하는 모든 것을 다 구현해보지는 못했습니다.
Suspense와 ErrorBoundary, useInView 훅까지 모두 한 번 구현해본 다음 다시 한 번 피드백 요청드려도 될까요?

2024-07-13 14:11 UTC, MiaJLee commented
> 안녕하세요 멘토님~!
> 
> 
> 
> 이번에도 정성껏 피드백해주셔서 정말 감사드립니다!
> 
> 
> 
> 피드백해주신 내용은 현재 반영했지만 아직까지 제가 원하는 모든 것을 다 구현해보지는 못했습니다.
> 
> Suspense와 ErrorBoundary, useInView 훅까지 모두 한 번 구현해본 다음 다시 한 번 피드백 요청드려도 될까요?


넵 내일 확인해볼게요-!

2024-07-13 15:14 UTC, cla6shade commented
멘토님 안녕하세요~!

Suspense, ErrorBoundary를 이용하여 render as you fetch 방식으로 설계해봤습니다!
클래스 컴포넌트를 사용해본적이 없어 ErrorBoundary 설계에서 버벅였고, IntersectionObserver을 처음 사용해봐서 시간이 조금 오래 걸렸던 것 같습니다.

시간나실때 리뷰해주시면 빠르게 반영해보겠습니다.
감사합니다!

2024-07-14 11:55 UTC, MiaJLee requested changes
세형님 고생하셨습니다~ 
리뷰 확인 부탁해요!

2024-07-14 11:55 UTC, MiaJLee commented on src/pages/ThemePage.tsx
> +} from 'react';
포맷팅 체크 한번 해주세요-!
확인해보니 린트 에러가 좀 나오네요

2024-07-14 11:55 UTC, MiaJLee commented on src/components/atoms/boundary/ErrorBoundary.tsx
본 컴포넌트만 클래스형으로 작성하신 이유가 있나요?

2024-07-14 12:15 UTC, cla6shade commented on src/pages/ThemePage.tsx
> +} from 'react';
넵, 수정 완료했습니다!

2024-07-14 12:24 UTC, cla6shade commented on src/components/atoms/boundary/ErrorBoundary.tsx
ErrorBoundary는 하위 컴포넌트들에서 에러가 발생한 경우 fallback UI를 렌더링하는 컴포넌트라고 공식 문서에 적혀있었는데, 아직 `function component로 작성할 방법이 없다`는 문구가 함께 있어서 따로 고려하지 않았던 것 같습니다..! (https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)

다른 라이브러리를 사용할까도 생각해봤지만, `라이브러리 의존성을 최소한으로 줄여보자`는 생각에 그대로 적어봤습니다.

2024-07-14 12:28 UTC, MiaJLee approved these changes
이번주도 고생 많으셨습니다-!

2024-07-14 12:28 UTC, merged

2024-07-14 12:29 UTC, cla6shade commented
감사합니다!
다음주에 4주차 PR로 찾아오겠습니다!!