충남대 FE_김지안_3주차 과제
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #74
Opened 2024-07-12 07:33 UTC by KimJi-An

안녕하세요, 멘토님! 충남대학교 김지안입니다.😊
3주차 과제 STEP 1~4 제출합니다.

### ❓질문
- 현재 Theme 페이지의 API 에러 처리를 하는 부분에서 각 HTTP 상태 코드에 대해 적절한 에러 메시지를 스위칭하여 사용자에게 보여주도록 해봤습니다. 400 에러는 "잘못된 요청입니다.", 404 에러는 "해당 테마의 상품을 찾을 수 없습니다." 등으로 처리했는데 좀 더 개선할 방법이 있을까요? 얼마나 많은 상태 코드를 처리하면 좋을지, 에러 메시지 관리를 더 효율적으로 할 방법에는 어떤 것이 있을지 궁금합니다.

2024-07-12 14:55 UTC, taehwanno requested changes
고생하셨습니다. 리뷰 피드백드려요.

2024-07-12 14:55 UTC, taehwanno commented on src/types/api.d.ts
> +export interface ProductOrderRequestBody {
`*.d.ts` 파일은 타입 정보가 없는 JavaScript 코드에 대한 타입 정보를 제공하기 위해 사용할 때가 많아요. 지금은 type 정보만 있어서 사용 가능하긴 하지만 프로젝트 구현 코드가 추후 추가될 수도 있기도 하고 `src/types/index.ts`와의 일관성을 맞추기 위해 `src/types/api.ts`로 변경하는게 좋아보여요.

- [`d.ts` files](https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#dts-files)

2024-07-12 14:55 UTC, taehwanno commented on src/pages/Theme/index.tsx
>    const { themeKey = '' } = useParams<{ themeKey: string }>();
themeKey가 없는 경우 하위 자식 컴포넌트인 `ThemeHeroSection`에서 [`/`로 이동](https://github.com/kimji-an/react-gift-goods-list/blob/281058d708d76fa17e0f42c4d74ae55a693a67b6/src/components/features/Theme/ThemeHeroSection/index.tsx#L25)되고 `ThemeGoodsSection`에서는 [useInfiniteQuery](https://github.com/kimji-an/react-gift-goods-list/blob/281058d708d76fa17e0f42c4d74ae55a693a67b6/src/components/features/Theme/ThemeGoodsSection/index.tsx#L21)에서 의미없는 요청이 발생할 거 같아요. 이를 한번 개선해보시겠어요?

2024-07-12 14:55 UTC, taehwanno commented on src/components/features/Theme/ThemeHeroSection/index.tsx
> +  }, [themeKey, navigate]);
`ThemeHeroSection`에서는 loading, error 처리가 없네요. 개선해보면 좋겠습니다!

2024-07-12 14:55 UTC, taehwanno commented on src/components/features/Theme/ThemeGoodsSection/index.tsx
> +    return <Message>{errorMessage}</Message>;
> 현재 Theme 페이지의 API 에러 처리를 하는 부분에서 각 HTTP 상태 코드에 대해 적절한 에러 메시지를 스위칭하여 사용자에게 보여주도록 해봤습니다. 400 에러는 "잘못된 요청입니다.", 404 에러는 "해당 테마의 상품을 찾을 수 없습니다." 등으로 처리했는데 좀 더 개선할 방법이 있을까요? 얼마나 많은 상태 코드를 처리하면 좋을지, 에러 메시지 관리를 더 효율적으로 할 방법에는 어떤 것이 있을지 궁금합니다.

보통은 백엔드 개발자와 협의한 HTTP API 명세에서 반환될 수 있는 HTTP 에러 코드를 중심으로 대응하게 됩니다. 400, 401, 403, 404, 422, 500, 502가 보통은 많이 쓰는 코드이고 여기에 유저 네트워크 환경에 따라 발생할 수 있는 네트워크 문제로 인한 에러가 있겠죠.

에러에 대한건 복구 가능한 에러인지, 아닌지에 따라 대응 방법을 다르게 가져가볼 수 있어요. 예를 들어, 네트워크 연결이 끊겨서 일시적으로 발생한 에러라면 재시도를 통해 복구해볼 수 있겠죠. 하지만, 403처럼 권한이 없을 떄는 재시도 가능하지 않아서 고객에게 안내하는 방법 밖에는 없겠죠.

제품 만드실 때 UX 측면에서 저는 아래 4가지 단계로 나눠서 바라보게끔 프론트엔드 엔지니어분들을 가이드 하긴 해요. 아래로 내려갈수록 사용자가 해야할 게 줄어들거나 아에 없애버릴 수 있으니까요.

1. 에러를 고객에게 인지시키기
1. 에러에 대한 대응 방법 안내하기
1. 에러에 대한 대응 방법 안내하면서 바로 시도할 수 있게 뷰 변화하기
1. 에러에 대한 대응 방법 안내없이 seamless 하게 재시도하기

2024-07-12 14:55 UTC, taehwanno commented on src/components/features/Theme/ThemeGoodsSection/index.tsx
> +    if (inView && hasNextPage) {
현재 코드 구조는 `fetchNextPage`를 통해 다음 페이지를 조회하고 있는 도중에 다시 `fetchNextPage`가 실행될 수 있겠네요. react-query의 [Infinite Queries](https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries#infinite-queries) 공식문서를 살펴보면 아래와 같은 내용이 있습니다.

한번 살펴보시고 대응해보시겠어요? race condition이라고도 표현하는데 JavaScript에서 비동기 코드 실행시 여러 코드가 실행될 때 실행되는 순서에 따라 결과가 달라지는 상황을 의미합니다. 비동기 코드가 여러번 실행될 수 있을 때 이전의 실행이 이미 끝났을 거라는 가정을 하는건 위험할 수 있어요.

> It's essential to understand that calling fetchNextPage while an ongoing fetch is in progress runs the risk of overwriting data refreshes happening in the background. This situation becomes particularly critical when rendering a list and triggering fetchNextPage simultaneously.

> Remember, there can only be a single ongoing fetch for an InfiniteQuery. A single cache entry is shared for all pages, attempting to fetch twice simultaneously might lead to data overwrites.

> If you intend to enable simultaneous fetching, you can utilize the { cancelRefetch: false } option (default: true) within fetchNextPage.

2024-07-13 09:56 UTC, KimJi-An commented on src/pages/Theme/index.tsx
>    const { themeKey = '' } = useParams<{ themeKey: string }>();
`ThemeGoodsSection`의 `useInfiniteQuery` 내에서 `enabled` 옵션을 사용해서 `themeKey`가 존재할 때만 `useInfiniteQuery`가 동작하도록 수정해봤습니다!

2024-07-13 13:54 UTC, KimJi-An commented on src/types/api.d.ts
> +export interface ProductOrderRequestBody {
의견주신대로 `api.ts`로 수정했습니다!

2024-07-13 14:12 UTC, KimJi-An commented on src/components/features/Theme/ThemeGoodsSection/index.tsx
> +    if (inView && hasNextPage) {
`useEffect` 내부에서 `inView`, `hasNextPage`, `!isFetchingNextPage` 조건을 확인해서 `fetchNextPage`를 호출하도록 하여 이미 `fetchNextPage`가 진행 중일 때 추가 호출하지 않도록 수정해보았습니다.

2024-07-13 14:26 UTC, KimJi-An commented on src/components/features/Theme/ThemeGoodsSection/index.tsx
> +    return <Message>{errorMessage}</Message>;
상세한 답변 감사합니다! 말씀해주신 에러의 복구 가능 여부와 4가지 단계로 나눠서 바라보는 방법 참고하여 에러 대응 방법에 대해 좀 더 생각해봐야겠습니다.

2024-07-13 14:31 UTC, KimJi-An commented on src/components/features/Theme/ThemeHeroSection/index.tsx
> +  }, [themeKey, navigate]);
`useQuery`를 사용하여 로딩 중에는 만들어둔 `Loading` 컴포넌트를, 에러 발생 시에는 "데이터를 불러오는 중에 문제가 발생했습니다." 라는 문구를 표시하도록 수정했습니다.

2024-07-14 06:13 UTC, taehwanno commented on src/pages/Theme/index.tsx
>    const { themeKey = '' } = useParams<{ themeKey: string }>();
```
└── Theme/index.tsx
        └── ThemeHeroSection
        └── ThemeGoodsSection
```

위에서 아래로 접근하면서 렌더링하게 될텐데요, `src/pages` 하위에서 관리되고 있는 각 페이지에 대응되는 컴포넌트에서 route parameter에 대한 부분을 처리해주면 하위 자식 컴포넌트에게 이를 처리할 책임이 흘러가지 않으니 일괄 처리할 수 있어서 보통 이런 경 우는 `Theme/index.tsx`에서 처리해주는게 좋습니다. 지금은 7번 라인에서 `themeKey`를 기본값을 빈 문자열로 주고 있는데 `undefined`일 경우 다른 페이지로 redirect 한다면 자식 컴포넌트를 이를 처리하지 않아도 되니까요.

2024-07-14 06:27 UTC, taehwanno approved these changes
고생하셨습니다!

2024-07-14 06:27 UTC, taehwanno commented on src/components/features/Theme/ThemeHeroSection/index.tsx
>    }
React에는 render phase, commit phase가 있습니다. 각각 화면에 그릴 요소가 무엇인지 파악하는 단계와 실제 DOM에 변경사항을 반영하는 단계로 나눠서 생각할 수 있어요. React에서 관리하는 상태 변화는 동기적으로 변화하는건 아니에요. 상태 변화는 batch 처리가 될 뿐만 아니라 concurrent mode에서 특정 컴포넌트의 렌더링은 여러번 될 수 있습니다. 

지금 작성해주신 코드는 render phase에서 `navigate`처럼 사이드 이펙트를 담은 함수를 실행하고 있기 때문에 추후 strict mode를 활성화하거나 concurrent mode 사용시 문제가 될 수 있기에 `useEffect`를 사용해서 처리해주시는게 좋겠습니다.

- [렌더링 그리고 커밋](https://ko.react.dev/learn/render-and-commit)

> 렌더링은 항상 순수한 계산:
> 
> - 동일한 입력에는 동일한 출력을 해야합니다. 동일한 입력이 주어지면 컴포넌트는 항상 동일한 JSX를 반환해야 합니다. (누군가 토마토 샐러드를 주문하면 그들은 양파가 있는 샐러드를 받으면 안 됩니다!)
> - 이전의 state를 변경해서는 안됩니다. 렌더링 전에 존재했던 객체나 변수를 변경해서는 안 됩니다. (누군가의 주문이 다른 사람의 주문을 변경해서는 안 됩니다.)
>
> 그렇지 않으면 코드베이스가 복잡해짐에 따라 혼란스러운 버그와 예측할 수 없는 동작이 발생할 수 있습니다. “Strict Mode”에서 개발할 때 React는 각 컴포넌트의 함수를 두 번 호출하여 순수하지 않은 함수로 인한 실수를 표면화하는데 도움을 받을 수 있습니다.

2024-07-14 06:28 UTC, merged