충남대 FE_강병현_3주차 과제 Step4
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #77
Opened 2024-07-12 08:40 UTC by kang-kibong

2024-07-14 07:08 UTC, taehwanno commented on .env
> +REACT_APP_BASE_URL=https://kakao-tech-campus-mock-server.vercel.app
.env는 민감한 값이 들어갈 수도 있어서 gitignore에 추가하고 커밋되지 않도록 관리하는게 좋습니다.

2024-07-14 07:08 UTC, taehwanno commented on src/components/features/Theme/index.ts
> +export { default as ThemeHeader } from './ThemeHeader';
여러 모듈을 다시 re-export 하는 이러한 코드 패턴을 barrel file pattern이라고 하는데요, 지금 프로젝트 수준에서는 별도 수정없이 사용해도 괜찮으나 프로젝트가 커졌을 때는 고려해볼만한 지점들이 있어서 언급만 해두고 넘어갈게요.

- [자바스크립트 에코시스템의 속도 향상 - 배럴(Barrel) 파일의 대실패](https://kofearticle.substack.com/p/korean-fe-article-barrel)

2024-07-14 07:08 UTC, taehwanno commented on src/hooks/useFetch.ts
> +  const memoizedApiCall = useCallback(apiCall, [apiCall]);
외부에서 주입한 API 함수를 여기서 메모이제이션 해서 어떤 이득을 얻을 수 있을까용?

2024-07-14 07:08 UTC, taehwanno commented on src/components/common/GoodsItem/index.tsx
> +      {renderRanking()}
```suggestion
      {rankingIndex && <Ranking {...{ rankingIndex }} />}
```

위처럼 inline 할 수 있을텐데 컴포넌트 내부의 함수로 추출해야하는 이유는 어떤걸까요?

2024-07-14 07:08 UTC, taehwanno commented on src/hooks/useInfiniteScroll.ts
> +}
`useInfiniteScroll`은 관찰하는 엘리먼트가 사용자의 눈에 보일 때 다음 페이지를 가져올 수 있는 상태라면 함수를 호출하도록 구현하고 있네요. 해당 hook은 hasNextpage, isFetchingNextPage에서 알 수 있듯이 react-query의 API에 영향을 많이 받은 인터페이스 방향인데요, 내부 구현을 보면 정작 알고 싶은건 전달된 fetchNextPage 함수를 실행할 수 있는지 없는지 여부라서 hasNextPage, isFetchingNextPage를 둘 다 데이터 의존성으로 가지기 보다는 계산된 결과값을 받아도 무리없어보여요.

```tsx
const ref = useInfiniteScroll(hasNextPage && isFetchingNextPage, fetchNextPage);
```

오히려 react-query가 변화하거나 여러 추가 조건들이 붙는다면 `useInfiniteScroll`을 사용하는 곳에서 수정해주시면 될뿐 내부 구현은 변화하지 않아도 되니까요.

2024-07-14 07:08 UTC, taehwanno commented on src/hooks/useGoodsItemListQuery.ts
> +  const queryKey = ['theneProduct', themeKey];
```suggestion
  const queryKey = ['themeProduct', themeKey];
```

오타인 거 같은데 한번 확인 부탁드릴게요.

2024-07-14 07:08 UTC, taehwanno commented on src/hooks/useGoodsItemListQuery.ts
> +    initialPageParam: '0',
```suggestion
    queryKey: ['themeProduct', themeKey],
    queryFn: ({ pageParam = '0' }) => {
      return getThemesProducts({ themeKey, pageToken: pageParam, maxResults: rowsPerPage });
    },
```

queryKey, queryFn은 object value로 바로 전달하지 않고 변수 선언해서 따로 분리해서 전달하게 되면 QueryFunctionContext처럼 타입 직접 지정해줘야해서 번거로울 수 있어요. 이런 경우에는 위에 제안드린 코드처럼 직접 전달하는걸 추천해요.

지금보니까 `useInfiniteQuery<ThemeProductsResponse, AxiosError>`에 전달한 타입이 잘못됐는지 pageParam이 `unknown`으로 뜨네요. 한번 개선해보시겠어요? 제안드린 코드 적용하고 `useInfiniteQuery`의 타입 변수에 아무런 타입 전달하지 않으니 잘 추론되는거 같네요.

2024-07-14 07:21 UTC, taehwanno requested changes
피드백 드립니다.

2024-07-14 07:21 UTC, taehwanno commented on src/apis/instance.ts
> +import axios, { AxiosError } from 'axios';
> 절대경로 https://github.com/types 어떻게 지정하나요?
> 
> types 디렉토리의 절대경로를 설정하기 위해서 tsconfig와 craco, eslint를 설정하였는데도 불구하고 파일을 가져올 수 없다는 에러가 발생합니다.
> 
> 제가 생각했을 때는 node_modules에 있는 types와 충돌이 일어나서 그런 것으로 예상되는데 어떻게 해결해야 하는지 궁금합니다.

원인은 말씀해주신 내용이 맞구요, 꼭 사용해야하는게 아니라면 가급적이면 이름 충돌나지 않도록 피해서 사용하시는게 좋습니다. `"@types/custom/*": ["src/types/custom/*"]`처럼 `@types` 하위에 별도 중첩 네임스페이스를 사용해서 피하는 방식도 있긴 한데 npm 패키지에서 설치한 타입인지 내부 프로젝트에서 직접 관리하는 코드인지 쉽게 알기 힘들기에 다른 이름을 쓰시는걸 추천드려요.

2024-07-17 07:33 UTC, kang-kibong commented on src/components/common/GoodsItem/index.tsx
> +      {renderRanking()}
가독성과 추후 유지보수하기 용이할 부분이라고 생각되서 해당 조건부 렌더링을 함수로 따로 분리하게되었습니다!

2024-07-17 09:23 UTC, kang-kibong commented on src/hooks/useFetch.ts
> +  const memoizedApiCall = useCallback(apiCall, [apiCall]);
API 호출 함수를 메모이제이션하여 동일한 함수 참조가 유지되도록 하고, 파라미터를 JSON 문자열로 변환하여 메모이제이션하면, 파라미터가 변경될 때만 이펙트가 다시 실행되니 불필요한 재렌더링과 API 호출을 막을 수 있을 것 같습니다!

2024-07-17 15:21 UTC, taehwanno approved these changes
3주차 과제 하신다고 고생하셨습니다. 4주차가 시작되었으니 거기에 집중해보시죠. 화이팅입니다.

2024-07-17 15:21 UTC, taehwanno commented on .env
> +REACT_APP_BASE_URL=https://kakao-tech-campus-mock-server.vercel.app
참고로 gitignore에 추가되기 전에 이미 커밋했다면 별도 git 명령어를 통해 제거해줘야하긴 합니다. 일단 넘어갈게요.

2024-07-17 15:21 UTC, taehwanno commented on src/hooks/useFetch.ts
> +  const memoizedApiCall = useCallback(apiCall, [apiCall]);
useFetch는 이제 쓰는 곳이 없어서 제거해도 될 거 같네요. 이전 코드 기준으로는 이미 useFetch를 사용하는 컴포넌트에서 리렌더링될 때 마다 `apiCall`로 전달하는 함수는 매번 재정의될 거라 여기서 메모이제이션은 큰 의미가 없을 수 있다는걸 말씀드리려 했네요.

2024-07-17 15:21 UTC, taehwanno commented on src/components/common/GoodsItem/index.tsx
> +      {renderRanking()}
관점이 다를 수 있는데 제가 가진 생각을 전달드려 볼게요. 컴포넌트 안에서 jsx를 반환하는 함수를 만들기 보다는 jsx로 인라인 하는게 위, 아래로 왔다 갔다 하지 않고 한 눈에 볼 수 있어서 쉽게 읽힌다점에서 가독성 측면에서는 더 나은 선택이라고 봐요. jsx를 반환하는 함수는 곧 컴포넌트로 추출될 수도 있다는 말인데 컴포넌트 안에서 매번 리렌더링시 재정의 되는 것도 좋은 방향일지 생각해볼만한 점이기도 합니다.

그리고 유지보수를 언급해주신 부분은 어떤 상황이 왔을 때 문제가 될 수 있을까요? 가독성, 유지보수성처럼 추상적이라 해석의 여지가 있는 단어를 사용할 때는 구체적인 맥락을 담아주셔야 서로의 다른 관점을 정렬하고 건설적인 논의를 할 수 있기에 한번쯤 생각해보시면 좋겠습니다.

2024-07-17 15:21 UTC, merged