경북대 FE_김민주_3주차 과제 Step1, 2
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #85
Opened 2024-07-12 12:20 UTC by joojjang

2024-07-14 06:33 UTC, joojjang commented
커스텀 훅을 사용하여 api 구현한 후 현재 GoodsRankingSection에 버그가 있는데, 
필터에 따라 target과 rank 파라미터가 바뀌지 않아서 계속 똑같은 파라미터로 요청이 가는 상황입니다. 
그래서 필터를 바꾸어도 응답 데이터가 바뀌지 않고 있습니다...

2024-07-15 00:31 UTC, danmin20 requested changes
수고하셨습니다~

2024-07-15 00:31 UTC, danmin20 commented on src/api/instance/index.tsx
> +const initInstance = (config: AxiosRequestConfig): AxiosInstance => {
함수로 만드신 이유가 있을까요?

2024-07-15 00:31 UTC, danmin20 commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +        <GoodsRankingList isError={isError} goodsList={data?.products ?? []} />
GoodsRankingList로 필터 옵션을 넘겨주고 GoodsRankingList 안에서 해당 필터값으로 쿼리를 요청해야 의도대로 동작할 것 같아요~

2024-07-15 00:31 UTC, danmin20 commented on src/components/features/Home/ThemeCategorySection/index.tsx
> +  const { data, isLoading, isError } = useThemes();
isFetching 옵션도 같이 확인해보시면 좋을 것 같아요~

2024-07-15 00:31 UTC, danmin20 commented on src/index.tsx
> +const queryClient = new QueryClient();
옵션들도 한번 알아보시고 설정해주시면 좋을 것 같아요~

2024-07-15 00:32 UTC, merged