강원대 FE_조중현 3주차 과제
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #86
Opened 2024-07-12 12:27 UTC by faddishcorn

안녕하세요! 3주차 과제  step 1,2,3,4단계 포함하여 제출하였습니다.  
감사합니다!

2024-07-14 12:34 UTC, lazy-sky requested changes
안녕하세요, 중현님

3주차 과제 수고하셨습니다!

2024-07-14 12:34 UTC, lazy-sky commented on src/api/hooks/useCurrentTheme.ts
> +    const themes: ThemeData[] = response.data.themes;
서버로부터 데이터를 정상적으로 불러오지 못했을 땐 문제가 발생할 가능성이 있지 않을까요?

2024-07-14 12:34 UTC, lazy-sky commented on src/api/hooks/useGetThemes.ts
> +const fetchThemes = async (): Promise<ThemeData[]> => {
다른 훅에서 페칭하는 부분도 이렇게 분리해 놓으면 더 좋을 거 같네요. 

더 나아가 모든 페치 부분들이 비슷한 로직을 사용하고 있는 유틸 함수 혹은 커스텀 훅으로 분리해서 재사용해보면 좋을 거 같습니다.

2024-07-14 12:34 UTC, lazy-sky commented on src/api/hooks/useGetThemes.ts
> +export const useGetThemes = () => {
use는 이미 Getter의 의미를 담고 있습니다.

2024-07-14 12:34 UTC, lazy-sky commented on src/api/hooks/useThemeGoods.ts
> +    ['themeGoods', themeKey],
쿼리키들을 하드 코딩해서 사용하고 있는데 이러면 나중에 어떤 문제가 생길 수 있을까요?

2024-07-14 12:34 UTC, lazy-sky commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  const queryClient = useQueryClient();
여기서 쿼리클라이언트를 선언하기에 더 좋은 위치는 없을까요?

2024-07-15 19:29 UTC, faddishcorn commented on src/api/hooks/useCurrentTheme.ts
> +    const themes: ThemeData[] = response.data.themes;
해당 훅을 사용한 컴포넌트에서 
if (isLoading) {
    return <div>로딩...</div>;
  }

  if (isError || !currentTheme) {
    return <div>데이터를 불러오는 중 문제가 발생하였습니다.</div>;
  }
같은 로직을 적용했었으나 결국은 훅 자체에서 에러에 대한 대응을 못한다는 점이 문제인 것 같습니다. 그래서 추가로 에러를 캐치할 수 있도록 추가로 작성하였습니다.

2024-07-15 19:29 UTC, faddishcorn commented on src/api/hooks/useGetThemes.ts
> +const fetchThemes = async (): Promise<ThemeData[]> => {
넵 fetchData라는 유틸로 만들어 분리를 해보았습니다. useGetRankingGoods에서 유틸을 사용해보려 했는데 필터에 따른 데이터 갱신이 안되어서 일단 에러에 대한 캐치문만 추가로 작성했습니다..ㅜㅜ

2024-07-15 19:29 UTC, faddishcorn commented on src/api/hooks/useThemeGoods.ts
> +    ['themeGoods', themeKey],
추후에 키 관리가 힘들어질 것 같습니다. 그래서 따로 키를 모아둔 파일을 만들어 import 하게끔 수정하였습니다.

2024-07-15 19:30 UTC, faddishcorn commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  const queryClient = useQueryClient();
일단 로직의 최상단에 위치하는 것이 나을것 같아 위로 옮겼습니다.. 혹시 다른 위치로 옮기는 것이 좋을까요..?

2024-07-16 01:28 UTC, lazy-sky commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +  const queryClient = useQueryClient();
아 제가 코드를 잘못봤었네요. `new QueryClient`로 선언됐다고 착각했었습니다.

2024-07-16 01:28 UTC, lazy-sky commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +            queryClient.invalidateQueries('rankingGoods');
키값의 변수화

2024-07-16 01:28 UTC, merged