강원대 FE_윤채연_3주차 과제 step2
kakao-tech-campus-2nd-step2/react-gift-goods-list pull request #96
Opened 2024-07-12 14:50 UTC by ychy61

안녕하세요 멘토님! 저는 강원대학교 윤채연입니다.
피드백을 위해 시간을 내주셔서 감사합니다!

step2 과제 중 각 API에서 Loading 상태에 대한 UI 대응에서 
테마 카테고리 같은 경우에는 Skeleton UI를 적용하는 것이 맞다고 생각이 들었는데,
시간 관계상 가능한 콘텐츠와 같이 Skeleton을 구현하는 것에 어려움이 있어 일괄로 Loading UI를 적용하여 아쉬움이 남았습니다.

그리고 과제 중 Http Status에 따라 Error를 다르게 처리해요.는 Axios 라이브러리를 이용하여 HTTP status error를 다루었습니다.
모든 컴포넌트와 페이지에서 일관되게 Error를 처리하는 방법으로 Axios 라이브러리를 사용하는 것이 재사용성이 좋을 것 같다는 생각이 들었습니다. 제가 다른 방법들을 충분히 찾아보지 못한 상태이고, 더 일반적인 방법이 있을까? 라는 의문이 들었습니다.

그럼 감사합니다.

2024-07-14 01:01 UTC, yujo11 requested changes
안녕하세요 채연님~

추가로 구현하고 싶은 부분이 있는 상황에서도 먼저 요구사항을 따라 기능을 구현하신 점은 잘 하신거 같아요 ㅎㅎ

에러 처리 관련해서는 현재 `handleRequestError`와 `handlerFetchError` 두 군데에서 이뤄지는 것으로 보이는데요. 이렇게 되면 한 군데에서 에러 처리를 하는 방식이 달라진다면 다른 함수도 그에 맞게 변경되어야 하는 의존성이 생길거 같아요

한 군데에서 이런 공통의 에러들이 관리되도록 구현해보셔도 좋을거 같습니다 ㅎㅎ

고생 많으셨습니다 ~~ 👍 👍 👍

2024-07-14 01:01 UTC, yujo11 commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +        )}
중첩된 삼항연산자는 코드 읽기를 어렵게 만드는데 이 부분을 개선해보시면 좋을거 같습니다 ㅎㅎ

2024-07-14 01:01 UTC, yujo11 commented on src/components/features/Theme/ThemeHeroSection/index.tsx
> +      } finally {
finally 까지 잘 사용해주셨네요 ㅎㅎ 👍

2024-07-14 01:01 UTC, yujo11 commented on src/components/features/Theme/ThemeHeroSection/index.tsx
> +  }
Suspense나 ErrorBoundary를 활용해봐도 좋을거 같아요 ㅎㅎ (반드시 사용하라는 얘기는 아닙니다)

2024-07-14 01:01 UTC, yujo11 commented on src/hooks/useFetchData.tsx
> +  const handleFetchError = (err: unknown) => {
중첩된 조건문이 많아져 코드 보기가 어려운데  코드를 보기 좋게 개선해 볼 수 있을까요?

2024-07-14 07:12 UTC, ychy61 commented on src/hooks/useFetchData.tsx
> +  const handleFetchError = (err: unknown) => {
넵! 제가 이 커스텀 훅으로 에러를 다루려고 시도하였다가 후에 handleRequestError에서만 에러 처리를 하기로 결정하였는데 미처 파일을 삭제하지 못하였네요..! 수정하도록 하겠습니다.

2024-07-14 07:13 UTC, ychy61 commented on src/components/features/Theme/ThemeHeroSection/index.tsx
> +  }
넵 피드백 감사합니다!

2024-07-14 07:13 UTC, ychy61 commented on src/components/features/Home/GoodsRankingSection/index.tsx
> +        )}
넵! 수정해보도록 하겠습니다!

2024-07-14 07:56 UTC, ychy61 reviewed
멘토님 피드백 감사합니다!

2024-07-16 09:25 UTC, yujo11 approved these changes
고생 많으셨어요 채연님 ~~

2024-07-16 09:25 UTC, merged